### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by olaoluwa-98** [stitchng/kwikng#2]
Please can this package be published on npm?

**Comment by stitchng** [comment]
Yes, it will be in a couple of days. It's almost ready

**Comment by olaoluwa-98** [comment]
I saw a couple of issues tho:

In this file at line 289,
https://github.com/stitchng/kwikng/blob/master/src/Kwik/index.js#L289
The parameter `apiKey` is not used. Also, `sandbox` and `live` URLs are the same

**Comment by stitchng** [comment]
Thanks for pointing this out!

There actually is no need for the  `apiKey` argument to the constructor as the API for Kwik Delivery does not support API Keys.

Also, the `sandbox` and `live` URLs are now differentiated.

**Comment by olaoluwa-98** [comment]
Okay, but since kwik always request for `access_token`. I think it should be passed into the constructor and automatically passed in the payload for every request. 

So anyone using the library would not have to pass it manually everytime

**Comment by stitchng** [comment]
@olaoluwa-98 your request has been handled. However only the _'domain_name'_ and _'is_production'_ flag are passed in as arguments to the constructor. Also, utilizing *inversion-of-control* you can make the AUTH request in a middleware ( expressjs ) to retrieve the `access_token`, `vendor_id`, `user_id` and `card_id` to be able set these once and have them automatically included in each requests' params. See [*README*](https://github.com/stitchng/kwikng/blob/master/README.md) code examples for more details: 

Also, this repo has now been published on [NPM](https://www.npmjs.com/package/kwik-node)

**Comment by stitchng** [comment]
Closing this issue out since there is no more activity
