### ISSUE TITLE
Error while running any method.

### ISSUE THREAD

**Issue by olaoluwa-98** [stitchng/kwikng#3]
Every method I have tried on the KwikClient always returns this error

```
The `body` option must be a plain Object or Array when the `form` or `json` option is used
```

**Comment by olaoluwa-98** [comment]
@stitchng  also, in this method `scheduleDeliveryTask`, amount expects a `String`. I'm guessing that's a mistake because `insurance_amount` and other number-like parameters expect `Number`

**Comment by stitchng** [comment]
Thanks for bringing this to my attention @olaoluwa-98 . We will start looking into it today

**Comment by stitchng** [comment]
@olaoluwa-98  This issue has been fixed in the latest version of this project on NPM -**v0.0.3**. Please report any other issues as you encounter them and we will try to fix promptly.

**Comment by stitchng** [comment]
@olaoluwa-98 for the `scheduleDeliveryTask`, if you check in the docs ( link in README ), the data type `amount` is a **String** so it's not a mistake (at least by the authors of the API docs). But, we understand what you mean. @isocroft has already double-checked this. As for `insurance_amount`, it is of type **Number** according to the API docs as well.

**Comment by olaoluwa-98** [comment]
@stitchng thanks for the update and clarification. However, `insurance_amount` is actually `string ` in the API docs so is `total_service_charge` and others.

**Comment by stitchng** [comment]
@olaoluwa-98 thanks for bringing this up. Please see latest version on NPM - **v0.0.5**

**Comment by isocroft** [comment]
@olaoluwa-98 are you still experiencing any more issues with this package/wrapper library ?

**Comment by olaoluwa-98** [comment]
For now, no.

**Comment by stitchng** [comment]
Ok good... Will close this out now then

**Comment by olaoluwa-98** [comment]
@isocroft I `insurance_amount` on `getEstimatedPriceForDeliveryTask` method is still Number

**Comment by stitchng** [comment]
@isocroft please check this out when you can.

**Comment by stitchng** [comment]
@olaoluwa-98 . please could you do a PR for this: *`insurance_amount` on **getEstimatedPriceForDeliveryTask()** method is still Number*

@isocroft has been really busy. Thanks

**Comment by olaoluwa-98** [comment]
Alright

**Comment by olaoluwa-98** [comment]
Seems like you've already adjusted it. The `Kwik.prototype.version` is still `0.0.2`. I think it needs to be bumped to `0.0.5`

**Comment by stitchng** [comment]
@olaoluwa-98 please find the latest version **v0.0.6** on npm. Thanks for all your help.
